package secure.com;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-09-04T15:09:06.622+01:00
 * Generated source version: 4.0.5
 *
 */
@WebService(targetNamespace = "urn:com.flexnet.lfs.webservice", name = "FulfillmentServiceInterface")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FulfillmentServiceInterface {

    @WebMethod
    @WebResult(name = "generateCloneDetectionReportResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GenerateCloneDetectionReportResponse generateCloneDetectionReport(

        @WebParam(partName = "request", name = "generateCloneDetectionReportRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GenerateCloneDetectionReportRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "obsoleteHostResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public ObsoleteHostResponse obsoleteHost(

        @WebParam(partName = "request", name = "obsoleteHostRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        ObsoleteHostRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getDeviceLicenseFileResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetDeviceLicenseFileResponse getDeviceLicenseFile(

        @WebParam(partName = "request", name = "getDeviceLicenseFileRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetDeviceLicenseFileRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "searchAddOnsResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public SearchAddOnsResponse searchAddOns(

        @WebParam(partName = "request", name = "searchAddOnsRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        SearchAddOnsRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "returnHostResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public ReturnHostResponse returnHost(

        @WebParam(partName = "request", name = "returnHostRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        ReturnHostRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "searchServedClientsResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public SearchServedClientsResponse searchServedClients(

        @WebParam(partName = "request", name = "searchServedClientsRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        SearchServedClientsRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "returnAddOnsResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public ReturnAddOnsResponse returnAddOns(

        @WebParam(partName = "request", name = "returnAddOnsRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        ReturnAddOnsRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getFilteredIDTypesForServerResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetFilteredIDTypesForServerResponse getFilteredIDTypesForServer(

        @WebParam(partName = "request", name = "getFilteredIDTypesForServerRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetFilteredIDTypesForServerRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "createHostResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public CreateHostResponse createHost(

        @WebParam(partName = "request", name = "createHostRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        CreateHostRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getConfigurationResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetConfigurationResponse getConfiguration(

        @WebParam(partName = "request", name = "getConfigurationRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetConfigurationRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "setConfigurationResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public SetConfigurationResponse setConfiguration(

        @WebParam(partName = "request", name = "setConfigurationRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        SetConfigurationRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "searchDeviceResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public SearchDeviceResponse searchDevice(

        @WebParam(partName = "request", name = "searchDeviceRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        SearchDeviceRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "searchDeviceModelsResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public SearchDeviceModelsResponse searchDeviceModels(

        @WebParam(partName = "request", name = "searchDeviceModelsRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        SearchDeviceModelsRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getAddOnMappingsCountResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetAddOnMappingsCountResponse getAddOnMappingsCount(

        @WebParam(partName = "request", name = "getAddOnMappingsCountRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetAddOnMappingsCountRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "searchSyncHistoryResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public SearchSyncHistoryResponse searchSyncHistory(

        @WebParam(partName = "request", name = "searchSyncHistoryRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        SearchSyncHistoryRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "deleteHostResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public DeleteHostResponse deleteHost(

        @WebParam(partName = "request", name = "deleteHostRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        DeleteHostRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "mapAddOnsResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public MapAddOnsResponse mapAddOns(

        @WebParam(partName = "request", name = "mapAddOnsRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        MapAddOnsRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "isRightsIdMappedResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public IsRightsIdMappedResponse isRightsIdMapped(

        @WebParam(partName = "request", name = "isRightsIdMappedRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        IsRightsIdMappedRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "returnDeviceResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public ReturnDeviceResponse returnDevice(

        @WebParam(partName = "request", name = "returnDeviceRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        ReturnDeviceRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getMaxMappableResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetMaxMappableResponse getMaxMappableWithoutCallback(

        @WebParam(partName = "request", name = "getMaxMappableWithoutCallbackRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetMaxMappableWithoutCallbackRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "capabilityResponseOutput", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public CapabilityResponseOutput getCapabilityResponse(

        @WebParam(partName = "request", name = "getCapabilityResponseInput", targetNamespace = "urn:com.flexnet.lfs.webservice")
        CapabilityResponseInput request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getDeviceResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetDeviceResponse getDevice(

        @WebParam(partName = "request", name = "getDeviceRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetDeviceRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getServerResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetServerResponse getDefaultServerForEnterprise(

        @WebParam(partName = "request", name = "getDefaultServerForEnterpriseRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetDefaultServerForEnterpriseRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "listPublishersResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public ListPublishersResponse listPublishers(

        @WebParam(partName = "request", name = "listPublishersRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        ListPublishersRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getAllowedIDTypesResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetAllowedIDTypesResponse getAllowedIDTypes(

        @WebParam(partName = "request", name = "getAllowedIDTypesRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetAllowedIDTypesRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "isCatalogItemMappedToLimitedSeriesResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public IsCatalogItemMappedToLimitedSeriesResponse isCatalogItemMappedToLimitedSeries(

        @WebParam(partName = "request", name = "isCatalogItemMappedToLimitedSeriesRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        IsCatalogItemMappedToLimitedSeriesRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getIdentityResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetIdentityResponse getIdentity(

        @WebParam(partName = "request", name = "getIdentityRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetIdentityRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "updateDeviceModelResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public UpdateDeviceModelResponse updateDeviceModel(

        @WebParam(partName = "request", name = "updateDeviceModelRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        UpdateDeviceModelRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "searchServersResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public SearchServersResponse searchServers(

        @WebParam(partName = "request", name = "searchServersRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        SearchServersRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "createDeviceModelResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public CreateDeviceModelResponse createDeviceModel(

        @WebParam(partName = "request", name = "createDeviceModelRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        CreateDeviceModelRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "usedByDeviceSeriesResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public UsedByDeviceSeriesResponse usedByDeviceSeries(

        @WebParam(partName = "request", name = "usedByDeviceSeriesRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        UsedByDeviceSeriesRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "addAddOnsResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public AddAddOnsResponse addAddOns(

        @WebParam(partName = "request", name = "addAddOnsRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        AddAddOnsRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "setHostedServerAdminPasswordResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public SetHostedServerAdminPasswordResponse setHostedServerAdminPassword(

        @WebParam(partName = "request", name = "setHostedServerAdminPasswordRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        SetHostedServerAdminPasswordRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getConfigurationMetadataResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetConfigurationMetadataResponse getConfigurationMetadata(

        @WebParam(partName = "request", name = "getConfigurationMetadataRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetConfigurationMetadataRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "isLicenseGeneratedResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public IsLicenseGeneratedResponse isLicenseGenerated(

        @WebParam(partName = "request", name = "isLicenseGeneratedRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        IsLicenseGeneratedRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "listDeviceModelsResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public ListDeviceModelsResponse listDeviceModels(

        @WebParam(partName = "request", name = "listDeviceModelsRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        ListDeviceModelsRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "moveDeviceResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public MoveDeviceResponse moveDevice(

        @WebParam(partName = "request", name = "moveDeviceRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        MoveDeviceRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "updateIdentityResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public UpdateIdentityResponse updateIdentity(

        @WebParam(partName = "request", name = "updateIdentityRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        UpdateIdentityRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "editServedClientResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public EditServedClientResponse editServedClient(

        @WebParam(partName = "request", name = "editServedClientRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        EditServedClientRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getDeviceModelResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetDeviceModelResponse getDeviceModel(

        @WebParam(partName = "request", name = "getDeviceModelRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetDeviceModelRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "createDeviceResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public CreateDeviceResponse createDevice(

        @WebParam(partName = "request", name = "createDeviceRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        CreateDeviceRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getAddOnMappingsResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetAddOnMappingsResponse getAddOnMappings(

        @WebParam(partName = "request", name = "getAddOnMappingsRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetAddOnMappingsRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "createServerResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public CreateServerResponse createServer(

        @WebParam(partName = "request", name = "createServerRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        CreateServerRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "processBinaryRequestOutput", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public ProcessBinaryRequestOutput processBinaryRequest(

        @WebParam(partName = "request", name = "processBinaryRequestInput", targetNamespace = "urn:com.flexnet.lfs.webservice")
        ProcessBinaryRequestInput request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getSignersResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetSignersResponse getSigners(

        @WebParam(partName = "request", name = "getSignersRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetSignersRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "createPublisherResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public CreatePublisherResponse createPublisher(

        @WebParam(partName = "request", name = "createPublisherRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        CreatePublisherRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "findServersForEnterpriseResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public FindServersForEnterpriseResponse findServersForEnterprise(

        @WebParam(partName = "request", name = "findServersForEnterpriseRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        FindServersForEnterpriseRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "createDeviceSeriesResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public CreateDeviceSeriesResponse createDeviceSeries(

        @WebParam(partName = "request", name = "createDeviceSeriesRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        CreateDeviceSeriesRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "isBaseProductUsedInLimitedSeriesResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public IsBaseProductUsedInLimitedSeriesResponse isBaseProductUsedInLimitedSeries(

        @WebParam(partName = "request", name = "isBaseProductUsedInLimitedSeriesRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        IsBaseProductUsedInLimitedSeriesRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getHostResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetHostResponse getHost(

        @WebParam(partName = "request", name = "getHostRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetHostRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getHostsResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetHostsResponse getHosts(

        @WebParam(partName = "request", name = "getHostsRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetHostsRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getSupportedHostIdTypesResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetSupportedHostIdTypesResponse getSupportedHostIdTypes(

        @WebParam(partName = "request", name = "getSupportedHostIdTypesRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetSupportedHostIdTypesRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "updateHostOwnerResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public UpdateHostOwnerResponse updateHostOwner(

        @WebParam(partName = "request", name = "updateHostOwnerRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        UpdateHostOwnerRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "isOwnerReferencedResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public IsOwnerReferencedResponse isOwnerReferenced(

        @WebParam(partName = "request", name = "isOwnerReferencedRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        IsOwnerReferencedRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "listDeviceSeriesResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public ListDeviceSeriesResponse listDeviceSeries(

        @WebParam(partName = "request", name = "listDeviceSeriesRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        ListDeviceSeriesRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "listIdentitiesResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public ListIdentitiesResponse listIdentities(

        @WebParam(partName = "request", name = "listIdentitiesRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        ListIdentitiesRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "moveDevicesResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public MoveDevicesResponse moveDevices(

        @WebParam(partName = "request", name = "moveDevicesRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        MoveDevicesRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "searchHostHistoryResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public SearchHostHistoryResponse searchHostHistory(

        @WebParam(partName = "request", name = "searchHostHistoryRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        SearchHostHistoryRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "createHostTypeResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public CreateHostTypeResponse createHostType(

        @WebParam(partName = "request", name = "createHostTypeRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        CreateHostTypeRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "listHostTypesResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public ListHostTypesResponse listHostTypes(

        @WebParam(partName = "request", name = "listHostTypesRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        ListHostTypesRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "createServerHostTypeResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public CreateServerHostTypeResponse createServerHostType(

        @WebParam(partName = "request", name = "createServerHostTypeRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        CreateServerHostTypeRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "moveServerResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public MoveServerResponse moveServer(

        @WebParam(partName = "request", name = "moveServerRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        MoveServerRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getServerHostTypeResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetServerHostTypeResponse getServerHostType(

        @WebParam(partName = "request", name = "getServerHostTypeRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetServerHostTypeRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "updateServerHostTypeResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public UpdateServerHostTypeResponse updateServerHostType(

        @WebParam(partName = "request", name = "updateServerHostTypeRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        UpdateServerHostTypeRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "updateMatchingHostOwnersResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public UpdateMatchingHostOwnersResponse updateMatchingHostOwners(

        @WebParam(partName = "request", name = "updateMatchingHostOwnersRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        UpdateMatchingHostOwnersRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "searchRequestHistoryResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public SearchRequestHistoryResponse searchRequestHistory(

        @WebParam(partName = "request", name = "searchRequestHistoryInput", targetNamespace = "urn:com.flexnet.lfs.webservice")
        SearchRequestHistoryInput request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "removeAddOnsResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public RemoveAddOnsResponse removeAddOns(

        @WebParam(partName = "request", name = "removeAddOnsRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        RemoveAddOnsRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "listServerHostTypesResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public ListServerHostTypesResponse listServerHostTypes(

        @WebParam(partName = "request", name = "listServerHostTypesRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        ListServerHostTypesRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getFeaturesResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetFeaturesResponse getFeatures(

        @WebParam(partName = "request", name = "getFeaturesRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetFeaturesRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getMaxMappableResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetMaxMappableResponse getMaxMappable(

        @WebParam(partName = "request", name = "getMaxMappableRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetMaxMappableRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "editDeviceResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public EditDeviceResponse editDevice(

        @WebParam(partName = "request", name = "editDeviceRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        EditDeviceRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "claimDeviceResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public ClaimDeviceResponse claimDevice(

        @WebParam(partName = "request", name = "claimDeviceRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        ClaimDeviceRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "createIdentityResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public CreateIdentityResponse createIdentity(

        @WebParam(partName = "request", name = "createIdentityRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        CreateIdentityRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getHostsForEntitlementTransferResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetHostsForEntitlementTransferResponse getHostsForEntitlementTransfer(

        @WebParam(partName = "request", name = "getHostsForEntitlementTransferRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetHostsForEntitlementTransferRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "detachUserResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public DetachUserResponse detachUser(

        @WebParam(partName = "request", name = "detachUserRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        DetachUserRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getPendingFulfillCountResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetPendingFulfillCountResponse getPendingFulfillCount(

        @WebParam(partName = "request", name = "getPendingFulfillCountRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetPendingFulfillCountRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "isCatalogItemMappedResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public IsCatalogItemMappedResponse isCatalogItemMapped(

        @WebParam(partName = "request", name = "isCatalogItemMappedRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        IsCatalogItemMappedRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getFilteredIDTypesForClientResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetFilteredIDTypesForClientResponse getFilteredIDTypesForClient(

        @WebParam(partName = "request", name = "getFilteredIDTypesForClientRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetFilteredIDTypesForClientRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "editHostResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public EditHostResponse editHost(

        @WebParam(partName = "request", name = "editHostRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        EditHostRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "updateDeviceSeriesResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public UpdateDeviceSeriesResponse updateDeviceSeries(

        @WebParam(partName = "request", name = "updateDeviceSeriesRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        UpdateDeviceSeriesRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "editServerResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public EditServerResponse editServer(

        @WebParam(partName = "request", name = "editServerRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        EditServerRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getServedClientResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetServedClientResponse getServedClient(

        @WebParam(partName = "request", name = "getServedClientRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetServedClientRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getServerResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetServerResponse getServer(

        @WebParam(partName = "request", name = "getServerRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetServerRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getDeviceSeriesResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetDeviceSeriesResponse getDeviceSeries(

        @WebParam(partName = "request", name = "getDeviceSeriesRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetDeviceSeriesRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "createTenantResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public CreateTenantResponse createTenant(

        @WebParam(partName = "request", name = "createTenantRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        CreateTenantRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "capabilityResponseOutput", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public CapabilityResponseOutput generateCapabilityResponse(

        @WebParam(partName = "request", name = "generateCapabilityResponseInput", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GenerateCapabilityResponseInput request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "generateLicenseFileResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GenerateLicenseFileResponse generateLicenseFile(

        @WebParam(partName = "request", name = "generateLicenseFileRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GenerateLicenseFileRequest request
    ) throws LFSFaultResponse_Exception;

    @WebMethod
    @WebResult(name = "getUsageSummaryResponse", targetNamespace = "urn:com.flexnet.lfs.webservice", partName = "response")
    public GetUsageSummaryResponse getUsageSummary(

        @WebParam(partName = "request", name = "getUsageSummaryRequest", targetNamespace = "urn:com.flexnet.lfs.webservice")
        GetUsageSummaryRequest request
    ) throws LFSFaultResponse_Exception;
}
