
package secure.com;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-09-04T15:09:06.603+01:00
 * Generated source version: 4.0.5
 */

@WebFault(name = "LFSFaultResponse", targetNamespace = "urn:com.flexnet.lfs.webservice")
public class LFSFaultResponse_Exception extends Exception {

    private LFSFaultResponse faultInfo;

    public LFSFaultResponse_Exception() {
        super();
    }

    public LFSFaultResponse_Exception(String message) {
        super(message);
    }

    public LFSFaultResponse_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public LFSFaultResponse_Exception(String message, LFSFaultResponse lfsFaultResponse) {
        super(message);
        this.faultInfo = lfsFaultResponse;
    }

    public LFSFaultResponse_Exception(String message, LFSFaultResponse lfsFaultResponse, Throwable cause) {
        super(message, cause);
        this.faultInfo = lfsFaultResponse;
    }

    public LFSFaultResponse getFaultInfo() {
        return this.faultInfo;
    }
}
